ALTER TABLE students
  MODIFY middle_name VARCHAR(100) NULL,
  MODIFY surname VARCHAR(100) NULL,
  MODIFY email VARCHAR(100) NULL,
  MODIFY phone VARCHAR(20) NULL,
  MODIFY father_name VARCHAR(100) NULL,
  MODIFY father_middle_name VARCHAR(100) NULL,
  MODIFY father_title ENUM('Mr', 'Late') DEFAULT 'Mr' NULL,
  MODIFY mother_name VARCHAR(100) NULL,
  MODIFY mother_middle_name VARCHAR(100) NULL,
  MODIFY mother_title ENUM('Mrs', 'Miss', 'Late') DEFAULT 'Mrs' NULL,
  MODIFY bus_no VARCHAR(20) NULL,
  MODIFY travel_mode VARCHAR(50) NULL,
  MODIFY travel_details VARCHAR(255) NULL,
  MODIFY subject_list VARCHAR(255) NULL,
  MODIFY fees DECIMAL(10,2) NULL,
  MODIFY gender VARCHAR(10) NULL,
  MODIFY dob DATE NULL,
  MODIFY address VARCHAR(255) NULL,
  MODIFY admission_date DATE NULL,
  MODIFY blood_group VARCHAR(10) NULL,
  MODIFY emergency_contact VARCHAR(50) NULL,
  MODIFY photo VARCHAR(255) NULL,
  MODIFY library_id VARCHAR(50) NULL,
  MODIFY certification VARCHAR(255) NULL; 